spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8088